---
- name: Check Disk Space and Notify on Telegram
  hosts: your_server
  tasks:
    - name: Get Disk Space Information
      shell: df / --output=avail --block-size=G | tail -n 1
      register: disk_space

    - name: Convert Disk Space to Numeric Value
      set_fact:
        available_space_gb: "{{ disk_space.stdout | regex_replace('G','') | int }}"

    - name: Send Notification to Telegram if Below 5GB
      when: "available_space_gb | int < 5"
      uri:
        url: "https://api.telegram.org/bot957532885:AAHGKNEHBthFlWTogxjcM45k4ZmoMHC15sc/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-1001770439301"
          text: "Warning: Low disk space! Available space: {{ available_space_gb }}GB"
        status_code: 200
        
