---
- name: Check Disk Space and Send Telegram Message
  hosts: all
  become: true

  tasks:
    - name: Get Disk Space Information
      shell: df -h / | awk 'NR==2 {print $4}'
      register: disk_space_output

    - name: Extract Second Line of df Output
      set_fact:
        second_line: "{{ ansible_hostname }} - {{ disk_space_output.stdout_lines }}"

    - name: Send Telegram Message
      uri:
        url: "https://api.telegram.org/bot957532885:AAHGKNEHBthFlWTogxjcM45k4ZmoMHC15sc/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "-1001770439301"
          text: "Disk space left on device: {{ second_line }}"
