---
- name: check disk space
  hosts: all
  tasks:
    - name: get disk usage
      command: df -h
      register: disk_usage
    - name: check disk space available
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage
    # - name: send discord message when disk space is over 80%
    #   uri:
    #     url: "your-webhook"
    #     method: POST
    #     body_format: json
    #     body: '{"content": "Disk space on {{ inventory_hostname }} is above 80%!"}'
    #     headers:
    #       Content-Type: application/json
    #     status_code: 204
    #   when: disk_usage.stdout[:-1]|int > 80
    - name: Send notify to Telegram
      community.general.telegram:
        token: '957532885:AAHGKNEHBthFlWTogxjcM45k4ZmoMHC15sc'
        api_args:
          chat_id: -1001770439301
          parse_mode: "markdown"
          text: "test"
          disable_web_page_preview: true
          disable_notification: true
