---
- name: Check if Ubuntu machine needs reboot and send Telegram notification
  hosts: all
  become: true

  tasks:
    - name: Check for reboot-required file
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Display message if reboot is required
      debug:
        msg: "Reboot is required on {{ inventory_hostname }}"   # You can customize the message as needed
      when: reboot_required.stat.exists

    - name: Send Telegram notification if reboot is required
      community.general.telegram:
        token: "957532885:AAHGKNEHBthFlWTogxjcM45k4ZmoMHC15sc"
        chat_id: "-1001770439301"
        text: "Reboot is required on {{ inventory_hostname }}"
      when: reboot_required.stat.exists
