---
- name: Restart Docker Container
  hosts: 192.168.1.53
  tasks:
    - name: Ensure Docker container is running
      docker_container:
        name: zigbee2mqtt
        state: started
        api_socket: unix://var/run/docker.sock
    - name: Restart Docker container
      docker_container:
        name: zigbee2mqtt
        state: restarted
        api_socket: unix://var/run/docker.sock
